default_host_prefix: 'www'
default_site: 'us'
site_locale_map:
  au: 'en-AU'
  nl: 'nl-NL'
  uk: 'en-GB'
  us: 'en-US'
  fr: 'fr-FR'
  de: 'de-DE'
  it: 'it-IT'
  se: 'sv-SE'
  es: 'es-ES'
  jp: 'ja-JP'
  ca: 'en-CA'
  es: 'es-ES'
  jp: 'ja-JP'
  ca: 'en-CA'

